import type { Doctor, Ally, Membership, Promotion, User, DiagnosisItem, CIE10Code, PaymentSettings } from "./types"

export const mockMemberships: Membership[] = [
  {
    id: "mem-1",
    name: "Membresía Mensual",
    price: 15,
    duration: "1 mes",
    benefits: [
      "Consultas médicas desde $12",
      "Descuento en laboratorio clínico",
      "Descuento en imágenes y rayos X",
      "Descuento en farmacia",
      "Descuento en odontología",
    ],
    discount: 70,
  },
  {
    id: "mem-2",
    name: "Membresía Anual",
    price: 150,
    duration: "12 meses",
    benefits: [
      "Consultas médicas desde $12",
      "Descuento en laboratorio clínico",
      "Descuento en imágenes y rayos X",
      "Descuento en farmacia",
      "Descuento en odontología",
      "Atención prioritaria",
      "Ahorro de $30 al año",
    ],
    discount: 70,
  },
]

export const mockDoctors: Doctor[] = [
  {
    id: "doc-1",
    name: "Dra. Saskia Rueda",
    specialty: "Pediatría",
    sectors: ["norte", "centro"],
    photo: "/doctora-pediatra-profesional.jpg",
    priceNormal: 40,
    priceMember: 12,
    modalities: ["presencial", "telemedicina"],
    schedule: [
      { day: 1, slots: ["09:00", "09:30", "10:00", "10:30", "11:00", "14:00", "14:30", "15:00"], sector: "norte" },
      { day: 3, slots: ["09:00", "09:30", "10:00", "10:30", "11:00"], sector: "centro" },
      { day: 5, slots: ["09:00", "09:30", "10:00", "10:30", "11:00", "14:00", "14:30"], sector: "norte" },
    ],
    email: "saskia.rueda@rch.com",
    phone: "0998765432",
    addresses: {
      norte: "Av. De los Shyris N34-256, Edif. Shyris Park, Of. 401",
      centro: "Calle García Moreno 567, Centro Médico Colonial, Piso 2",
      sur: "",
    },
  },
  {
    id: "doc-2",
    name: "Dr. Carlos Mendoza",
    specialty: "Medicina General",
    sectors: ["sur", "centro"],
    photo: "/doctor-medicina-general-profesional.jpg",
    priceNormal: 40,
    priceMember: 12,
    modalities: ["presencial", "telemedicina", "domicilio"],
    schedule: [
      {
        day: 1,
        slots: ["08:00", "08:30", "09:00", "09:30", "10:00", "14:00", "14:30", "15:00", "15:30"],
        sector: "sur",
      },
      { day: 2, slots: ["08:00", "08:30", "09:00", "09:30", "10:00"], sector: "centro" },
      { day: 4, slots: ["08:00", "08:30", "09:00", "09:30", "10:00", "14:00", "14:30", "15:00"], sector: "sur" },
    ],
    email: "carlos.mendoza@rch.com",
    phone: "0998765433",
    addresses: {
      norte: "",
      centro: "Calle Montúfar 789, Consultorio Médico Centro, Of. 102",
      sur: "Av. Rodrigo de Chávez S45-123, Centro Médico Sur",
    },
  },
  {
    id: "doc-3",
    name: "Dra. María Fernández",
    specialty: "Ginecología",
    sectors: ["norte"],
    photo: "/doctora-ginecologia-profesional.jpg",
    priceNormal: 50,
    priceMember: 15,
    modalities: ["presencial"],
    schedule: [
      { day: 2, slots: ["10:00", "10:30", "11:00", "11:30", "14:00", "14:30", "15:00"], sector: "norte" },
      { day: 4, slots: ["10:00", "10:30", "11:00", "11:30", "14:00", "14:30"], sector: "norte" },
    ],
    email: "maria.fernandez@rch.com",
    phone: "0998765434",
    addresses: {
      norte: "Av. República E7-456, Torre Médica Norte, Of. 505",
      centro: "",
      sur: "",
    },
  },
  {
    id: "doc-4",
    name: "Dr. Jorge Sánchez",
    specialty: "Psicología",
    sectors: ["centro"],
    photo: "/professional-psychologist.png",
    priceNormal: 45,
    priceMember: 14,
    modalities: ["presencial", "telemedicina"],
    schedule: [
      { day: 1, slots: ["09:00", "10:00", "11:00", "14:00", "15:00", "16:00"], sector: "centro" },
      { day: 3, slots: ["09:00", "10:00", "11:00", "14:00", "15:00", "16:00"], sector: "centro" },
      { day: 5, slots: ["09:00", "10:00", "11:00"], sector: "centro" },
    ],
    email: "jorge.sanchez@rch.com",
    phone: "0998765435",
    addresses: {
      norte: "",
      centro: "Calle Benalcázar 234, Centro de Salud Mental, Of. 301",
      sur: "",
    },
  },
  {
    id: "doc-5",
    name: "Dr. Andrés Castro",
    specialty: "Cardiología",
    sectors: ["norte", "sur"],
    photo: "/doctor-cardiologo-profesional.jpg",
    priceNormal: 60,
    priceMember: 18,
    modalities: ["presencial"],
    schedule: [
      { day: 2, slots: ["08:00", "08:30", "09:00", "09:30", "10:00"], sector: "norte" },
      { day: 4, slots: ["14:00", "14:30", "15:00", "15:30", "16:00"], sector: "sur" },
    ],
    email: "andres.castro@rch.com",
    phone: "0998765436",
    addresses: {
      norte: "Av. Naciones Unidas E10-567, Clínica Cardiovascular, Piso 3",
      centro: "",
      sur: "Av. Mariscal Sucre S34-890, Centro Cardiológico Sur",
    },
  },
  {
    id: "doc-6",
    name: "Dra. Patricia López",
    specialty: "Dermatología",
    sectors: ["centro", "sur"],
    photo: "/doctora-dermatologa-profesional.jpg",
    priceNormal: 55,
    priceMember: 16,
    modalities: ["presencial"],
    schedule: [
      { day: 1, slots: ["10:00", "10:30", "11:00", "11:30", "14:00", "14:30"], sector: "centro" },
      { day: 3, slots: ["10:00", "10:30", "11:00", "11:30"], sector: "sur" },
      { day: 5, slots: ["14:00", "14:30", "15:00", "15:30"], sector: "centro" },
    ],
    email: "patricia.lopez@rch.com",
    phone: "0998765437",
    addresses: {
      norte: "",
      centro: "Calle Guayaquil 456, Centro Dermatológico, Of. 201",
      sur: "Av. Teniente Hugo Ortiz S45-678, Consultorio Sur",
    },
  },
  {
    id: "doc-7",
    name: "Dr. Luis Ramírez",
    specialty: "Traumatología",
    sectors: ["norte"],
    photo: "/doctor-traumatologo-profesional.jpg",
    priceNormal: 55,
    priceMember: 16,
    modalities: ["presencial"],
    schedule: [
      { day: 2, slots: ["09:00", "09:30", "10:00", "10:30", "11:00"], sector: "norte" },
      { day: 4, slots: ["09:00", "09:30", "10:00", "10:30", "11:00", "14:00", "14:30"], sector: "norte" },
    ],
    email: "luis.ramirez@rch.com",
    phone: "0998765438",
    addresses: {
      norte: "Av. 6 de Diciembre N32-789, Clínica Traumatológica, Of. 402",
      centro: "",
      sur: "",
    },
  },
  {
    id: "doc-8",
    name: "Dra. Ana Martínez",
    specialty: "Endocrinología",
    sectors: ["sur", "centro"],
    photo: "/doctora-endocrinologa-profesional.jpg",
    priceNormal: 50,
    priceMember: 15,
    modalities: ["presencial", "telemedicina"],
    schedule: [
      { day: 1, slots: ["08:00", "08:30", "09:00", "09:30", "10:00"], sector: "sur" },
      { day: 3, slots: ["14:00", "14:30", "15:00", "15:30", "16:00"], sector: "centro" },
      { day: 5, slots: ["08:00", "08:30", "09:00", "09:30"], sector: "sur" },
    ],
    email: "ana.martinez@rch.com",
    phone: "0998765439",
    addresses: {
      norte: "",
      centro: "Calle Venezuela 567, Centro Endocrinológico, Piso 4",
      sur: "Av. Maldonado S28-234, Consultorio Médico Sur",
    },
  },
  {
    id: "doc-9",
    name: "Dr. Roberto Vargas",
    specialty: "Oftalmología",
    sectors: ["norte", "centro"],
    photo: "/professional-ophthalmologist.png",
    priceNormal: 50,
    priceMember: 15,
    modalities: ["presencial"],
    schedule: [
      { day: 2, slots: ["10:00", "10:30", "11:00", "11:30", "14:00", "14:30"], sector: "norte" },
      { day: 4, slots: ["10:00", "10:30", "11:00", "11:30"], sector: "centro" },
    ],
    email: "roberto.vargas@rch.com",
    phone: "0998765440",
    addresses: {
      norte: "Av. República E7-890, Centro Oftalmológico, Of. 601",
      centro: "Calle Montúfar 345, Clínica Visual Centro, Piso 2",
      sur: "",
    },
  },
  {
    id: "doc-10",
    name: "Dra. Gabriela Torres",
    specialty: "Nutrición",
    sectors: ["centro", "sur"],
    photo: "/doctora-nutricionista-profesional.jpg",
    priceNormal: 40,
    priceMember: 12,
    modalities: ["presencial", "telemedicina"],
    schedule: [
      { day: 1, slots: ["09:00", "10:00", "11:00", "14:00", "15:00", "16:00"], sector: "centro" },
      { day: 3, slots: ["09:00", "10:00", "11:00", "14:00", "15:00"], sector: "sur" },
      { day: 5, slots: ["09:00", "10:00", "11:00"], sector: "centro" },
    ],
    email: "gabriela.torres@rch.com",
    phone: "0998765441",
    addresses: {
      norte: "",
      centro: "Calle García Moreno 890, Centro de Nutrición, Of. 103",
      sur: "Av. Quitumbe Ñan S34-567, Consultorio Nutricional Sur",
    },
  },
]

export const mockAllies: Ally[] = [
  {
    id: "ally-1",
    name: "Farmacia Salud Norte",
    type: "pharmacy",
    sector: "norte",
    address: "Av. De los Shyris N34-123",
    phone: "023456789",
    discount: 15,
    photo: "/farmacia-moderna.jpg",
  },
  {
    id: "ally-2",
    name: "Farmacia Económica Centro",
    type: "pharmacy",
    sector: "centro",
    address: "Calle García Moreno 456",
    phone: "023456790",
    discount: 15,
    photo: "/farmacia.jpg",
  },
  {
    id: "ally-3",
    name: "Farmacia MediSur",
    type: "pharmacy",
    sector: "sur",
    address: "Av. Maldonado S28-567",
    phone: "023456791",
    discount: 15,
    photo: "/farmacia-local.jpg",
  },
  {
    id: "ally-4",
    name: "Laboratorio Clínico LabSalud",
    type: "laboratory",
    sector: "norte",
    address: "Av. República E7-234",
    phone: "023456792",
    discount: 20,
    photo: "/laboratorio-clinico.jpg",
  },
  {
    id: "ally-5",
    name: "Laboratorio Diagnóstico Centro",
    type: "laboratory",
    sector: "centro",
    address: "Calle Montúfar 789",
    phone: "023456793",
    discount: 20,
    photo: "/laboratorio-medico.jpg",
  },
  {
    id: "ally-6",
    name: "Lab Sur Express",
    type: "laboratory",
    sector: "sur",
    address: "Av. Quitumbe Ñan S34-890",
    phone: "023456794",
    discount: 20,
    photo: "/laboratorio.jpg",
  },
  {
    id: "ally-7",
    name: "Centro de Imagen Norte",
    type: "imaging",
    sector: "norte",
    address: "Av. Naciones Unidas E10-345",
    phone: "023456795",
    discount: 25,
    photo: "/centro-de-imagenes-rayos-x.jpg",
  },
  {
    id: "ally-8",
    name: "Imagen y Diagnóstico Centro",
    type: "imaging",
    sector: "centro",
    address: "Calle Venezuela 234",
    phone: "023456796",
    discount: 25,
    photo: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "ally-9",
    name: "RxSur - Centro de Imagen",
    type: "imaging",
    sector: "sur",
    address: "Av. Mariscal Sucre S45-678",
    phone: "023456797",
    discount: 25,
    photo: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "ally-10",
    name: "Clínica Dental Sonrisa Norte",
    type: "dental",
    sector: "norte",
    address: "Av. 6 de Diciembre N32-456",
    phone: "023456798",
    discount: 20,
    photo: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "ally-11",
    name: "Odontología Integral Centro",
    type: "dental",
    sector: "centro",
    address: "Calle Benalcázar 567",
    phone: "023456799",
    discount: 20,
    photo: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "ally-12",
    name: "DentalSur",
    type: "dental",
    sector: "sur",
    address: "Av. Teniente Hugo Ortiz S67-890",
    phone: "023456800",
    discount: 20,
    photo: "/placeholder.svg?height=150&width=150",
  },
]

export const mockPromotions: Promotion[] = [
  {
    id: "promo-1",
    title: "Chequeo Ejecutivo Completo",
    description: "Evaluación médica integral para ejecutivos",
    price: 89,
    includes: [
      "Consulta médica general",
      "Exámenes de laboratorio completos",
      "Electrocardiograma",
      "Radiografía de tórax",
    ],
    validUntil: "2025-12-31",
    image: "/placeholder.svg?height=300&width=400",
  },
  {
    id: "promo-2",
    title: "Paquete Cardio Completo",
    description: "Evaluación cardiovascular completa",
    price: 120,
    includes: ["Consulta con cardiólogo", "Electrocardiograma", "Ecocardiograma", "Prueba de esfuerzo"],
    validUntil: "2025-12-31",
    image: "/placeholder.svg?height=300&width=400",
  },
  {
    id: "promo-3",
    title: "Paquete Mujer Integral",
    description: "Chequeo ginecológico y preventivo",
    price: 95,
    includes: ["Consulta ginecológica", "Papanicolaou", "Ecografía pélvica", "Mamografía"],
    validUntil: "2025-12-31",
    image: "/placeholder.svg?height=300&width=400",
  },
  {
    id: "promo-4",
    title: "Control Pediátrico Anual",
    description: "Evaluación completa para niños",
    price: 65,
    includes: [
      "Consulta pediátrica",
      "Control de crecimiento",
      "Exámenes de laboratorio básicos",
      "Orientación nutricional",
    ],
    validUntil: "2025-12-31",
    image: "/placeholder.svg?height=300&width=400",
  },
]

export const mockSpecialties = [
  "Medicina General",
  "Pediatría",
  "Ginecología",
  "Cardiología",
  "Dermatología",
  "Psicología",
  "Traumatología",
  "Endocrinología",
  "Oftalmología",
  "Nutrición",
  "Odontología",
  "Otorrinolaringología",
]

export const mockDiagnosisCodes: DiagnosisItem[] = [
  { code: "J00", description: "Rinofaringitis aguda (resfriado común)" },
  { code: "J06.9", description: "Infección aguda de las vías respiratorias superiores" },
  { code: "K21.9", description: "Enfermedad por reflujo gastroesofágico" },
  { code: "M79.3", description: "Dolor muscular" },
  { code: "R51", description: "Cefalea" },
  { code: "R50.9", description: "Fiebre no especificada" },
  { code: "A09", description: "Gastroenteritis aguda" },
  { code: "I10", description: "Hipertensión esencial primaria" },
  { code: "E11.9", description: "Diabetes mellitus tipo 2" },
  { code: "J45.9", description: "Asma no especificada" },
  { code: "L20.9", description: "Dermatitis atópica" },
  { code: "M25.5", description: "Dolor articular" },
  { code: "R10.4", description: "Dolor abdominal" },
  { code: "N39.0", description: "Infección de vías urinarias" },
  { code: "H10.9", description: "Conjuntivitis no especificada" },
  { code: "J02.9", description: "Faringitis aguda" },
  { code: "K30", description: "Dispepsia funcional" },
  { code: "M54.5", description: "Lumbago" },
  { code: "R05", description: "Tos" },
  { code: "F41.9", description: "Trastorno de ansiedad" },
  { code: "E66.9", description: "Obesidad" },
  { code: "E78.5", description: "Hiperlipidemia" },
  { code: "I25.1", description: "Enfermedad cardíaca isquémica" },
  { code: "J20.9", description: "Bronquitis aguda" },
  { code: "L30.9", description: "Dermatitis no especificada" },
  { code: "M19.9", description: "Artrosis no especificada" },
  { code: "N76.0", description: "Vaginitis aguda" },
  { code: "R11", description: "Náusea y vómito" },
  { code: "R42", description: "Mareo y vértigo" },
  { code: "Z00.0", description: "Examen médico general" },
]

export const mockCIE10Codes: CIE10Code[] = [
  { code: "J00", description: "Resfriado común" },
  { code: "J06.9", description: "Infección respiratoria aguda" },
  { code: "K29.7", description: "Gastritis no especificada" },
  { code: "I10", description: "Hipertensión esencial" },
  { code: "E11", description: "Diabetes mellitus tipo 2" },
  { code: "M54.5", description: "Lumbago" },
  { code: "N39.0", description: "Infección de vías urinarias" },
  { code: "J02.9", description: "Faringitis aguda" },
  { code: "R51", description: "Cefalea" },
  { code: "K30", description: "Dispepsia" },
  { code: "J45.9", description: "Asma no especificada" },
  { code: "E66.9", description: "Obesidad" },
  { code: "F41.9", description: "Trastorno de ansiedad" },
  { code: "L20.9", description: "Dermatitis atópica" },
  { code: "M25.5", description: "Dolor articular" },
  { code: "H10.9", description: "Conjuntivitis" },
  { code: "A09", description: "Gastroenteritis aguda" },
  { code: "R10.4", description: "Dolor abdominal" },
  { code: "J20.9", description: "Bronquitis aguda" },
  { code: "E78.5", description: "Hiperlipidemia" },
  { code: "R05", description: "Tos" },
  { code: "R11", description: "Náusea y vómito" },
  { code: "R42", description: "Mareo y vértigo" },
  { code: "I25.1", description: "Enfermedad cardíaca isquémica" },
  { code: "L30.9", description: "Dermatitis no especificada" },
  { code: "M19.9", description: "Artrosis no especificada" },
  { code: "N76.0", description: "Vaginitis aguda" },
  { code: "Z00.0", description: "Examen médico general" },
  { code: "R50.9", description: "Fiebre no especificada" },
  { code: "M79.3", description: "Dolor muscular" },
]

export const mockPaymentSettings: PaymentSettings = {
  retentionPercentage: 40,
  paymentMethods: {
    transfer: true,
    card: true,
  },
  bankInfo: {
    bankName: "Banco Pichincha",
    accountNumber: "2100012345",
    accountType: "Ahorros",
    ownerName: "SEDCO SALUD S.A.",
    ownerId: "1792345678001",
  },
}

export const mockInitialUsers: User[] = [
  {
    id: "user-patient-1",
    email: "paciente@demo.com",
    password: "demo123",
    role: "patient",
    name: "Juan Pérez",
    cedula: "1712345678",
    phone: "0987654321",
    membershipActive: false,
  },
  {
    id: "user-doctor-1",
    email: "doctor@demo.com",
    password: "demo123",
    role: "doctor",
    name: "Dra. Saskia Rueda",
    cedula: "1798765432",
    phone: "0998765432",
    doctorId: "doc-1",
  },
  {
    id: "user-admin-1",
    email: "admin@demo.com",
    password: "demo123",
    role: "admin",
    name: "Admin RCH",
    cedula: "1787654321",
    phone: "0987654322",
  },
  {
    id: "user-ally-1",
    email: "aliado@demo.com",
    password: "demo123",
    role: "ally",
    name: "Farmacia Salud Norte",
    allyId: "ally-1",
  },
]
